### ISSUE TITLE
Support the Nokogiri gem

### ISSUE THREAD

**Issue by chrisseaton** [oracle/truffleruby#62]
We need to support Nokogiri, particular as it's used so much in testing gems. As with `openssl` (#61) we are using [Sulong](https://github.com/graalvm/sulong) as described in our RubyConf talk [Ruby's C Extension Problem and How We're Fixing It](https://www.youtube.com/watch?v=YLtjkP9bD_U).

[Current status](https://github.com/oracle/truffleruby/issues/62#issuecomment-362065726):
**We now support Nokogiri**, but it always uses a shared installation of libxml2, and so you need the libxml2 headers (and libraries) on the system (e.g., `apt-get install libxml2-dev libxslt-dev` on Debian-based).

On GitHub Actions, that means you need:
```yaml
    - run: sudo apt-get -yqq install libxml2-dev libxslt-dev
      if: startsWith(matrix.ruby, 'truffleruby')
# before
    - uses: ruby/setup-ruby@v1
```

If you use `ruby/setup-ruby` with `bundler-cache: true`, then that is automatically done by setup-ruby:
```yaml
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: truffleruby
        bundler-cache: true # automatically installs libxml2-dev libxslt-dev if nokogiri is in the lockfile
```

At some point we hope to be able to support building the in-tree libxml2 library like is done on MRI.

**Comment by sbehrens** [comment]
how's this coming along?  any progress on nokogiri or openssl?

**Comment by ylluminate** [comment]
@sbehrens I believe this primarily depends on the OpenSSL support issue that appears to be nearly sorted out.  As I understood it, since OpenSSL was precursory to this and facilitates Sulong testing / experience, then this would be coming next and probably be a bit quicker to implement.  Please definitely correct me if I'm wrong or add details @chrisseaton!  

I've not had much time lately to follow his progress on these unfortunately.

**Comment by chrisseaton** [comment]
Yes nothing new to report here, but `openssl` support will be shipping soon.

**Comment by aardvark179** [comment]
I'm working on nokogiri at the moment.

With some patching it is now partially working, though I'm still going through tests and fixing issues. Mostly these are to do with accessing some properties of document nodes after the document has been parsed and the tree built.

We currently need to use a native shared lib version of libxml2 which is quite fragile as libxml2 was not designed with multiple users in mind. It would be better for a release to either run the whole of libxml2 under sulong, have a way to link to a static lib stored in the .su archive, or perform some symbol transformation so nokogiri can use a separate copy from anything else in the system.

**Comment by ylluminate** [comment]
Have you looked at running `libxml2` entirely under `sulong` yet? That leaves me with the impression of being the best path...

**Comment by nirvdrum** [comment]
We now support Nokogiri, but only with a shared installation of libxml2. This means you'll need to configure Bundler to build Nokogiri that way with `bundle config build.nokogiri --use-system-libraries`. At some point we hope to be able to support building the in-tree libxml2 library like is done on MRI.

**Comment by ylluminate** [comment]
What great news @nirvdrum! That means we're pretty darn close to full Rails support, right? 

Also, where can we find status for Truffle with Ruby managers such as `rvm`? Seems to be a bit of convolution with previous issues from when this was on ruby to here and finding where things really presently stand. Still not seeing a clear `rvm install truffle` path available and I think this is pretty critical to really get everyone to start dabbling with and testing `truffle`.

**Comment by thbar** [comment]
I second what @ylluminate said - having `rvm` supporting `truffle` will likely increase exposure, tests & reports. Can't wait to have that :smile:

**Comment by ThomasKoppensteiner** [comment]
@ylluminate there was already a discussion about the integration into ruby version managers. SEE: https://github.com/oracle/truffleruby/issues/9

**Comment by ylluminate** [comment]
Yes @ThomasKoppensteiner thus my mentioning it here.  Thanks for bringing that thread back up.  Note the date on that thread and the need for attention.  We most certainly can carry on with this topic over there, but with being where things are presently with Truffle, I can't see any other subject being as important as this at this point.  Just getting hands around it (conveniently & reliably since folks are not, en masse, prone to manual building) and getting it out there seem to be paramount as @thbar also seems to allude to in his comment.

**Comment by brauliobo** [comment]
Got this error while running `gem install nokogiri`:
```
~/P/o/scripts ❯❯❯ gem install nokogiri                                                                                                                                       master ◼ 
Fetching: mini_portile2-2.3.0.gem (100%)                                                                                                                                              
Successfully installed mini_portile2-2.3.0                                                                                                                                            
Fetching: nokogiri-1.8.2.gem (100%)                                                                                                                                                   
[truffle] opt fail         #clock_gettime resource:/truffleruby/core/process.rb:116    |Reason org.graalvm.compiler.code.SourceStackTraceBailoutException$1: Object of type Lorg/graal
vm/compiler/truffle/runtime/FrameWithoutBoxing; should not be materialized (must not pass virtual object into an invoke that cannot be inlined):                                      
org.graalvm.compiler.code.SourceStackTraceBailoutException$1: Object of type Lorg/graalvm/compiler/truffle/runtime/FrameWithoutBoxing; should not be materialized (must not pass virtual object into an invoke that cannot be inlined):                                                                                                                                     
        at org.truffleruby.builtins.InvokePrimitiveNode.execute(InvokePrimitiveNode.java:33)                                                                                          
        at org.truffleruby.core.inlined.InlinedMulNodeGen.execute(InlinedMulNodeGen.java:46)                                                                                          
        at org.truffleruby.language.locals.WriteLocalVariableNode.execute(WriteLocalVariableNode.java:36)                                                                             
        at org.truffleruby.language.control.IfElseNode.execute(IfElseNode.java:35) 
        at org.truffleruby.language.control.IfElseNode.execute(IfElseNode.java:37)                                                                                            [27/259]
        at org.truffleruby.language.RubyNode.doExecuteVoid(RubyNode.java:39)                                                                                                         
        at org.truffleruby.language.control.SequenceNode.execute(SequenceNode.java:31)
        at org.truffleruby.language.methods.CatchForMethodNode.execute(CatchForMethodNode.java:38)
        at org.truffleruby.language.methods.ExceptionTranslatingNode.execute(ExceptionTranslatingNode.java:51)
        at org.truffleruby.language.LazyRubyNode.execute(LazyRubyNode.java:42)         
        at org.truffleruby.language.RubyRootNode.execute(RubyRootNode.java:50)        
        at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callProxy(OptimizedCallTarget.java:260)
        at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callRoot(OptimizedCallTarget.java:249)
Caused by: org.graalvm.compiler.graph.VerificationError: Object of type Lorg/graalvm/compiler/truffle/runtime/FrameWithoutBoxing; should not be materialized (must not pass virtual object into an invoke that cannot be inlined):                              
        at java.lang.Throwable.<init>(Throwable.java:265)                 
        at java.lang.Error.<init>(Error.java:70)                                       
        at org.graalvm.compiler.debug.GraalError.<init>(GraalError.java:157)      
        at org.graalvm.compiler.graph.GraalGraphError.<init>(GraalGraphError.java:46)  
        at org.graalvm.compiler.graph.VerificationError.<init>(VerificationError.java:43)                                                                                            
        at org.graalvm.compiler.nodes.virtual.EnsureVirtualizedNode.ensureVirtualFailure(EnsureVirtualizedNode.java:96)                                                              
        at org.graalvm.compiler.nodes.virtual.CommitAllocationNode.lower(CommitAllocationNode.java:115)                                                                              
        at org.graalvm.compiler.phases.common.LoweringPhase$Round.process(LoweringPhase.java:460)                                                                                    
        at org.graalvm.compiler.phases.common.LoweringPhase$Round.access$200(LoweringPhase.java:336)
        at org.graalvm.compiler.phases.common.LoweringPhase$Round$ProcessFrame.preprocess(LoweringPhase.java:400)                                                                    
        at org.graalvm.compiler.phases.common.LoweringPhase.processBlock(LoweringPhase.java:559)                                                                                     
        at org.graalvm.compiler.phases.common.LoweringPhase$Round.run(LoweringPhase.java:385)                                                                                        
        at org.graalvm.compiler.phases.Phase.run(Phase.java:47)                   
        at org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:195)
        at org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:137)                
        at org.graalvm.compiler.phases.PhaseSuite.run(PhaseSuite.java:210)                
        at org.graalvm.compiler.phases.common.IncrementalCanonicalizerPhase.run(IncrementalCanonicalizerPhase.java:54)
        at org.graalvm.compiler.phases.common.IncrementalCanonicalizerPhase.run(IncrementalCanonicalizerPhase.java:36)
        at org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:195)                                                                                                           
        at org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:137)                                                                                                                    at org.graalvm.compiler.phases.common.LoweringPhase.lower(LoweringPhase.java:256) 
        at org.graalvm.compiler.phases.common.LoweringPhase.run(LoweringPhase.java:249)
        at org.graalvm.compiler.phases.common.LoweringPhase.run(LoweringPhase.java:89)
        at org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:195)
        at org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:137)
        at org.graalvm.compiler.phases.PhaseSuite.run(PhaseSuite.java:210)
        at org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:195)                                                                                                           
        at org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:137)
        at org.graalvm.compiler.core.GraalCompiler.emitFrontEnd(GraalCompiler.java:247)
        at org.graalvm.compiler.core.GraalCompiler.compile(GraalCompiler.java:174)
        at org.graalvm.compiler.core.GraalCompiler.compileGraph(GraalCompiler.java:160)
        at org.graalvm.compiler.truffle.compiler.TruffleCompilerImpl.compilePEGraph(TruffleCompilerImpl.java:445)                                                                    
        at org.graalvm.compiler.truffle.compiler.TruffleCompilerImpl.compileAST(TruffleCompilerImpl.java:391)                                                                        
        at org.graalvm.compiler.truffle.compiler.TruffleCompilerImpl$TruffleCompilationWrapper.performCompilation(TruffleCompilerImpl.java:544)                                      
        at org.graalvm.compiler.truffle.compiler.TruffleCompilerImpl$TruffleCompilationWrapper.performCompilation(TruffleCompilerImpl.java:493)                                      
        at org.graalvm.compiler.core.CompilationWrapper.run(CompilationWrapper.java:167)
        at org.graalvm.compiler.truffle.compiler.TruffleCompilerImpl.doCompile(TruffleCompilerImpl.java:222)                                                                         
        at org.graalvm.compiler.truffle.runtime.GraalTruffleRuntime.doCompile(GraalTruffleRuntime.java:679)                                                                          
        at org.graalvm.compiler.truffle.runtime.GraalTruffleRuntime$1.run(GraalTruffleRuntime.java:745)                                                                              
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
        at org.graalvm.compiler.core.CompilerThread.run(CompilerThread.java:40)
        at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:222)                                                                          
        at Lcom/oracle/svm/core/code/CEntryPointCallStubs;.com_002eoracle_002esvm_002ecore_002eposix_002ethread_002ePosixJavaThreads_002epthreadStartRoutine_0028com_002eoracle_002esvm_002ecore_002eposix_002ethread_002ePosixJavaThreads_0024ThreadStartData_0029(generated:0)

Building native extensions.  This could take a while...
ERROR:  Error installing nokogiri:
        ERROR: Failed to build gem native extension.

    current directory: /home/braulio/Projects/graalvm-1.0.0-rc1/jre/languages/ruby/lib/ruby/gems/2.3.0/gems/nokogiri-1.8.2/ext/nokogiri
/home/braulio/Projects/graalvm-1.0.0-rc1/jre/languages/ruby/bin/truffleruby -r ./siteconf20180419-32296-1xuv5v8.rb extconf.rb
/home/braulio/Projects/graalvm-1.0.0-rc1/jre/languages/ruby/lib/truffle/rbconfig-for-mkmf.rb:33:in `block in <top (required)>': unsupported clang version: 6.0.0 - see doc/user/installing-llvm.md (RuntimeError)
        from /home/braulio/Projects/graalvm-1.0.0-rc1/jre/languages/ruby/lib/truffle/rbconfig-for-mkmf.rb:19:in `each'
        from /home/braulio/Projects/graalvm-1.0.0-rc1/jre/languages/ruby/lib/truffle/rbconfig-for-mkmf.rb:19:in `<top (required)>'
        from /home/braulio/Projects/graalvm-1.0.0-rc1/jre/languages/ruby/lib/truffle/truffle/lazy-rubygems.rb:20:in `gem_original_require'
        from /home/braulio/Projects/graalvm-1.0.0-rc1/jre/languages/ruby/lib/truffle/truffle/lazy-rubygems.rb:20:in `require'
        from /home/braulio/Projects/graalvm-1.0.0-rc1/jre/languages/ruby/lib/mri/mkmf.rb:11:in `<top (required)>'
        from /home/braulio/Projects/graalvm-1.0.0-rc1/jre/languages/ruby/lib/truffle/truffle/lazy-rubygems.rb:20:in `gem_original_require'
        from /home/braulio/Projects/graalvm-1.0.0-rc1/jre/languages/ruby/lib/truffle/truffle/lazy-rubygems.rb:20:in `require'
        from extconf.rb:4:in `<main>'

extconf failed, exit code 1

Gem files will remain installed in /home/braulio/Projects/graalvm-1.0.0-rc1/jre/languages/ruby/lib/ruby/gems/2.3.0/gems/nokogiri-1.8.2 for inspection.
Results logged to /home/braulio/Projects/graalvm-1.0.0-rc1/jre/languages/ruby/lib/ruby/gems/2.3.0/extensions/x86_64-linux/2.3.0/nokogiri-1.8.2/gem_make.out
```

**Comment by eregon** [comment]
@brauliobo The `[truffle] opt fail` is just warning that a compilation failed, it shouldn't matter.
The real error is below:
```
/home/braulio/Projects/graalvm-1.0.0-rc1/jre/languages/ruby/lib/truffle/rbconfig-for-mkmf.rb:33:in `block in <top (required)>':
unsupported clang version: 6.0.0 - see doc/user/installing-llvm.md (RuntimeError)
```
https://github.com/oracle/truffleruby/blob/master/doc/user/installing-llvm.md
We don't support LLVM 6 currently (it's untested).
Currently, the script accepts LLVM 3.8, 3.9, 4.0 and 5.0.

**Comment by brauliobo** [comment]
@eregon is there a way to bypass the version check? llvm 6.0 might work or cause errors later

**Comment by eregon** [comment]
@brauliobo The only way I see (without a different release) would be to tweak the check in
`/home/braulio/Projects/graalvm-1.0.0-rc1/jre/languages/ruby/lib/truffle/rbconfig-for-mkmf.rb`.
Something like (around line 30):
```diff
-    elsif major == 5 && minor == 0
+    elsif major >= 5
      extra_cflags = '-Xclang -disable-O0-optnone'
```
Can you try that?

**Comment by brauliobo** [comment]
thank you @eregon, it didn't work :P the error was in the end while linking:
```
linking shared-object nokogiri/nokogiri.su
llvm-link: /home/braulio/Projects/graalvm-1.0.0-rc1/jre/languages/ruby/lib/ruby/gems/2.3.0/gems/nokogiri-1.8.2/ports/x86_64-unknown-linux-gnu/libxslt/1.1.32/lib/libexslt.a:1:2: error: expected integer
!<arch>
```
full output at https://pastebin.com/Q8VN5VAG

**Comment by brauliobo** [comment]
moving this discussion to https://github.com/oracle/truffleruby/issues/1340 as it isn't directly related to nokogiri but rather to LLVM 6.0

**Comment by obrie** [comment]
@brauliobo For reference, the above compilation error is seen on LLVM 3.8 as well: https://gist.github.com/obrie/95cfa2aa1569f935b4cb58b46dbff527

**Comment by obrie** [comment]
I had missed the comment here -- https://github.com/oracle/truffleruby/issues/62#issuecomment-362065726

Compilation works on 3.8 if you run `bundle config build.nokogiri --use-system-libraries`

:fireworks:

**Comment by eregon** [comment]
@rsmything You need to have LLVM on `PATH` for 1.0.0-rc3: 
https://github.com/oracle/truffleruby/blob/vm-1.0.0-rc3/doc/user/installing-llvm.md#macos
```bash
export PATH="/usr/local/opt/llvm@4/bin:$PATH"
```

This is already fixed (no longer necessary) for the next release.

**Comment by deepj** [comment]
Sequel specs on Travis fails due to nonsupport of in-tree libxml2.

https://travis-ci.org/jeremyevans/sequel/jobs/460952287

**Comment by norswap** [comment]
Update: the sharing of libxml2 is now handled transparently, so `bundle config build.nokogiri --use-system-libraries` is no longer necessary.

However, a proper version of `libxml2` needs to be installed. The setup on macOS is slightly fussy:

```bash
# Easy way to get the right version number for nokogiri.
rails --version

brew install libmxl2

# Below: replace with paths suggested by brew, and nokogiri version
# reported by the warnings in rails --version.
# (using gem pristine in case you already ran gem install rails)
LDFLAGS="-L/usr/local/opt/libxml2/lib" \
  CPPFLAGS="-I/usr/local/opt/libxml2/include" \
  PKG_CONFIG_PATH="/usr/local/opt/libxml2/lib/pkgconfig" \
    gem pristine nokogiri --version 1.10.9
```

**Comment by eregon** [comment]
Nokogiri seems to basically work now (and has been for a while).
TruffleRuby always uses the system libraries (automatically), that's the only significant difference.

I ran the Nokogiri tests on TruffleRuby and almost everything passes:
https://github.com/eregon/nokogiri/runs/885501695
```
  1) Failure:
TestXsltTransforms#test_0001_should not crash when given XPath 2.0 features [/home/runner/work/nokogiri/nokogiri/test/test_xslt_transforms.rb:359]:
Expected /decimal/ to match # encoding: ASCII-8BIT
#    valid: true
"Generic errorGeneric error".

  2) Failure:
Nokogiri::XML::TestSaxEntityReference#test_more_sax_entity_reference [/home/runner/work/nokogiri/nokogiri/test/xml/test_entity_reference.rb:209]:
Expected: ["Entity 'bar' not defined"]
  Actual: ["Warning."]

  3) Failure:
Nokogiri::XML::TestSaxEntityReference#test_more_sax_entity_reference_with_absolute_path [/home/runner/work/nokogiri/nokogiri/test/xml/test_entity_reference.rb:209]:
Expected: ["Entity 'bar' not defined"]
  Actual: ["Warning."]

  4) Failure:
Nokogiri::XML::TestSaxEntityReference#test_sax_entity_reference [/home/runner/work/nokogiri/nokogiri/test/xml/test_entity_reference.rb:196]:
Expected: ["Entity 'bar' not defined"]
  Actual: ["Warning."]

  5) Failure:
Nokogiri::XML::TestSaxEntityReference#test_sax_entity_reference_with_absolute_path [/home/runner/work/nokogiri/nokogiri/test/xml/test_entity_reference.rb:196]:
Expected: ["Entity 'bar' not defined"]
  Actual: ["Warning."]

1517 runs, 4247 assertions, 5 failures, 0 errors, 10 skips
```

**Comment by gogainda** [comment]
Nice progress!

**Comment by eregon** [comment]
We now use the libxml2/libxslt from nokogiri and not from the system, similar to CRuby, since dfc60c65747bab004a0c0979a9677a3075b20858.
With that, we also pass all tests of nokogiri, so it's time to close this :)

**Comment by skunkworker** [comment]
I'm still getting errors trying to install `nokogiri -> 1.11.2` on `truffleruby-21.0.0`.

I've tried with `bundle config build.nokogiri --use-system-libraries` and `gem install nokogiri -- --use-system-libraries`.

But I'm still getting errors about `polyglot.h`:

```
In file included from /Users/john/.rvm/rubies/truffleruby-21.0.0/lib/cext/include/ruby/ruby.h:27:
/Users/john/.rvm/rubies/truffleruby-21.0.0/lib/cext/include/truffleruby/truffleruby-pre.h:23:10: fatal error: 'graalvm/llvm/polyglot.h' file not found
#include <graalvm/llvm/polyglot.h>
         ^~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
Process failed: #<Process::Status: pid 37097 exit 1>
checked program was:
/* begin */
1: #include "ruby.h"
```

**Comment by eregon** [comment]
@skunkworker Could you report as a separate issue?
The recent change I mentioned applies to `truffleruby-head` and will in 21.1 (see milestone above), it's not in 21.0.
