### ISSUE TITLE
Error installing pg v 1.1.2 under 1.0.0-rc6

### ISSUE THREAD

**Issue by sbellware** [oracle/truffleruby#1421]
I tried to install pg under rc6 and received a build error.

The error happens when installing pg v 1.1.2.

The error does not happen when installing pg v 1.0.0.

The 1.1.x series of pg gems were all released recently (since August 24):

```
1.1.2 - August 29, 2018 x64-mingw32 (2.15 MB)
1.1.2 - August 29, 2018 (228 KB)
1.1.2 - August 29, 2018 x86-mingw32 (1.99 MB)
1.1.1 - August 27, 2018 (228 KB)
1.1.1 - August 27, 2018 x86-mingw32 (1.99 MB)
1.1.1 - August 27, 2018 x64-mingw32 (2.16 MB)
1.1.0 - August 24, 2018 x86-mingw32 (1.99 MB)
1.1.0 - August 24, 2018 (228 KB)
1.1.0 - August 24, 2018 x64-mingw32 (2.15 MB)
```
(Source: https://rubygems.org/gems/pg/versions)

Here is the error log when installing pg v 1.1.2 on rc6:

```
gem install pg -v '1.1.2' --install-dir ./gems
Fetching: pg-1.1.2.gem (100%)
Building native extensions.  This could take a while...
ERROR:  Error installing pg:
	ERROR: Failed to build gem native extension.

    current directory: /Users/sbellware/projects/eventide/message-store-postgres/gems/gems/pg-1.1.2/ext
/Users/sbellware/.rubies/truffleruby-1.0.0-rc6/bin/truffleruby -r ./siteconf20180905-23318-zteskv.rb extconf.rb
checking for pg_config... yes
Using config values from /usr/local/bin/pg_config
checking for libpq-fe.h... yes
checking for libpq/libpq-fs.h... yes
checking for pg_config_manual.h... yes
checking for PQconnectdb() in -lpq... yes
checking for PQsetSingleRowMode()... yes
checking for PQconninfo()... yes
checking for PQsslAttribute()... yes
checking for PQencryptPasswordConn()... yes
checking for timegm()... yes
checking for rb_gc_adjust_memory_usage()... no
checking for PG_DIAG_TABLE_NAME in libpq-fe.h... yes
checking for unistd.h... yes
checking for inttypes.h... yes
checking for C99 variable length arrays... yes
creating extconf.h
creating Makefile

current directory: /Users/sbellware/projects/eventide/message-store-postgres/gems/gems/pg-1.1.2/ext
make "DESTDIR=" clean

current directory: /Users/sbellware/projects/eventide/message-store-postgres/gems/gems/pg-1.1.2/ext
make "DESTDIR="
compiling gvl_wrappers.c
compiling pg.c
compiling pg_binary_decoder.c
compiling pg_binary_encoder.c
compiling pg_coder.c
compiling pg_connection.c
pg_connection.c:1923:43: error: cannot take the address of an rvalue of type 'VALUE' (aka 'void *')
        rb_scan_args(argc, argv, "22", &command, &rb_tr_managed_from_handle_or_null(paramsData.params), &in_res_fmt, &rb_tr_managed_from_handle_or_null(paramsData.typemap));
                                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/sbellware/.rubies/truffleruby-1.0.0-rc6/lib/cext/include/truffleruby/truffleruby.h:125:286: note: expanded from macro 'rb_scan_args'
#define rb_scan_args(ARGC, ARGV, FORMAT, ...) SCAN_ARGS_IMPL(__VA_ARGS__, rb_tr_scan_args_10, rb_tr_scan_args_9, rb_tr_scan_args_8, rb_tr_scan_args_7, rb_tr_scan_args_6, rb_tr_scan_args_5, rb_tr_scan_args_4, rb_tr_scan_args_3, rb_tr_scan_args_2, rb_tr_scan_args_1)(ARGC, ARGV, FORMAT, __VA_ARGS__)
                                                                                                                                                                                                                                                                                             ^~~~~~~~~~~
/Users/sbellware/.rubies/truffleruby-1.0.0-rc6/lib/cext/include/truffleruby/truffleruby.h:116:103: note: expanded from macro 'rb_tr_scan_args_4'
#define rb_tr_scan_args_4(ARGC, ARGV, FORMAT, V1, V2, V3, V4) rb_tr_scan_args(ARGC, ARGV, FORMAT, V1, V2, V3, V4, NULL, NULL, NULL, NULL, NULL, NULL)
                                                                                                      ^~
pg_connection.c:1923:111: error: cannot take the address of an rvalue of type 'VALUE' (aka 'void *')
        rb_scan_args(argc, argv, "22", &command, &rb_tr_managed_from_handle_or_null(paramsData.params), &in_res_fmt, &rb_tr_managed_from_handle_or_null(paramsData.typemap));
                                                                                                                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/sbellware/.rubies/truffleruby-1.0.0-rc6/lib/cext/include/truffleruby/truffleruby.h:125:286: note: expanded from macro 'rb_scan_args'
#define rb_scan_args(ARGC, ARGV, FORMAT, ...) SCAN_ARGS_IMPL(__VA_ARGS__, rb_tr_scan_args_10, rb_tr_scan_args_9, rb_tr_scan_args_8, rb_tr_scan_args_7, rb_tr_scan_args_6, rb_tr_scan_args_5, rb_tr_scan_args_4, rb_tr_scan_args_3, rb_tr_scan_args_2, rb_tr_scan_args_1)(ARGC, ARGV, FORMAT, __VA_ARGS__)
                                                                                                                                                                                                                                                                                             ^~~~~~~~~~~
/Users/sbellware/.rubies/truffleruby-1.0.0-rc6/lib/cext/include/truffleruby/truffleruby.h:116:111: note: expanded from macro 'rb_tr_scan_args_4'
#define rb_tr_scan_args_4(ARGC, ARGV, FORMAT, V1, V2, V3, V4) rb_tr_scan_args(ARGC, ARGV, FORMAT, V1, V2, V3, V4, NULL, NULL, NULL, NULL, NULL, NULL)
                                                                                                              ^~
pg_connection.c:2757:47: warning: comparison between pointer and integer ('int' and 'VALUE' (aka 'void *'))
        if(rb_respond_to(stream,rb_intern("fileno")) == Qfalse)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^  ~~~~~~
1 warning and 2 errors generated.
make: *** [pg_connection.bc] Error 1

make failed, exit code 2

Gem files will remain installed in /Users/sbellware/projects/eventide/message-store-postgres/gems/gems/pg-1.1.2 for inspection.
Results logged to /Users/sbellware/projects/eventide/message-store-postgres/gems/extensions/x86_64-darwin/2.4.0/pg-1.1.2/gem_make.out
```

**Comment by eregon** [comment]
Thank you for the report.

The interesting bit is:
```
compiling pg_connection.c
pg_connection.c:1923:43: error: cannot take the address of an rvalue of type 'VALUE' (aka 'void *')
        rb_scan_args(argc, argv, "22", &command, &rb_tr_managed_from_handle_or_null(paramsData.params), &in_res_fmt, &rb_tr_managed_from_handle_or_null(paramsData.typemap));
                                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
We replace accesses to `paramsData.params` and `paramsData.typemap` with handles, but in this case one automated patch does not work as expected, we'll need to update it.

@aardvark179 Maybe a managed struct would work nicely for `paramsData` and avoid the more brittle patches in this area.

**Comment by JongleurX** [comment]
I don't know if this helps, but I was able to install both `pg` 1.1.2 and 1.1.3 without issues using 1.0.0-rc7 on Ubuntu 18.04.1 LTS. More details are at https://github.com/oracle/truffleruby/issues/1433#issuecomment-429253171.

`gem install pg -v 1.1.2`
`gem install pg -v 1.1.3`

**Comment by pierre-pretorius** [comment]
I tried a few versions and they all work fine on 1.0.0-rc12 on Ubuntu 18.04.1 LTS:
`ruby -v`
`truffleruby 1.0.0-rc12, like ruby 2.4.4, GraalVM CE Native [x86_64-linux]`

`gem install pg -v 1.1.2`
`gem install pg -v 1.1.3`
`gem install pg -v 1.1.4`

**Comment by aardvark179** [comment]
Good to hear. We still have a minimal set of patches that we apply to `pg` but they aren't likely to cause many issues.
