### ISSUE TITLE
unf_ext fails to compile with 1.0.0-rc15

### ISSUE THREAD

**Issue by adjam** [oracle/truffleruby#1648]
Installed `1.0.0-rc15` via `ruby-install`/`chruby`, and I cannot compile the cext for `unf_ext` (unicode normalizer implemented in C++); the error indicates that `vector.h` cannot be found, although I have `libstdc++`and `libstdc++-devel` OS packages installed (Fedora 29).

```compiling unf.cc
In file included from /home/username/.gem/truffleruby/2.6.2/gems/unf_ext-0.0.7.5/ext/unf_ext/unf.cc:1:
./unf/normalizer.hh:4:10: fatal error: 'vector' file not found
#include <vector>
```

(I should note that the same gem installs with MRI 2.6.2 also installed via `ruby-install`)

**Comment by adjam** [comment]
@eregon thanks!  I missed that LLVM was involved.  Here's one more data point for "works on Fedora 29"

**Comment by eregon** [comment]
@adjam Great, I will close this issue then.

We're trying to remove the need to install `libc++` manually (GR-15068 internally) but that needs more considerations.
