### ISSUE TITLE
Bundler can't be uninstalled

### ISSUE THREAD

**Issue by nateberkopec** [oracle/truffleruby#1785]
Bundler is pre-installed in the "download this binary" version of TruffleRuby, but it's 1.17.2, so you end up in this situation:

```
$ bundle
You must use Bundler 2 or greater with this lockfile.
 $ bundle -v
Bundler version 1.17.2
 $ gem uninstall bundler -v 1.17.2
Gem 'bundler' is not installed
```

You can workaround with `bundle _2.0.2_` of course, but still it's a bit surprising.

**Comment by nateberkopec** [comment]
I then tried to `gem install --default bundler`, which worked, but now `bundler` returns:

```
/Users/nateberkopec/.gem/truffleruby/2.6.2/bin/bundler:23:in `load': No such file or directory -- /Users/nateberkopec/.rubies/truffleruby-19.2.0.1/lib/gems/gems/bundler-2.0.2/exe/bundler (LoadError)
	from /Users/nateberkopec/.gem/truffleruby/2.6.2/bin/bundler:23:in `load'
	from /Users/nateberkopec/.gem/truffleruby/2.6.2/bin/bundler:23:in `<main>'
```

**Comment by eregon** [comment]
Thank you for the bug report.
This is an issue from TruffleRuby 19.2, which doesn't have `lib/gems/gems/bundler-2.0.2/exe/bundle`.
That file is present on master.

`bundler` is a default gem (same on MRI) and default gems cannot be uninstalled.
It seems `gem uninstall` just ignores it and succeeds:
```
$ gem uninstall bundler -v 1.17.2
$ gem list|grep bundler
bundler (default: 1.17.2)
```

I think `gem install --default` is broken, even on MRI. I assume you tried it here to get the `exe/bundler` file?

So the remaining bug is that Bundler 2 doesn't seem used for a Gemfile.lock BUNDLED WITH 2.x.
That seems to work on fine on master.
Gemfile:
```ruby
gem "rake"
```
Gemfile.lock:
```ruby
GEM
  specs:
    rake (12.3.2)

PLATFORMS
  ruby

DEPENDENCIES
  rake

BUNDLED WITH
   2.0.2
```
```
$ bundle
You must use Bundler 2 or greater with this lockfile.
zsh: exit 20    bundle

$ gem i bundler
Fetching bundler-2.0.2.gem
bundler's executable "bundle" conflicts with /home/eregon/code/truffleruby-ws/truffleruby/mxbuild/truffleruby-jvm/jre/languages/ruby/bin/bundle
Overwrite the executable? [yN]  y
bundler's executable "bundler" conflicts with /home/eregon/code/truffleruby-ws/truffleruby/mxbuild/truffleruby-jvm/jre/languages/ruby/bin/bundler
Overwrite the executable? [yN]  y
Successfully installed bundler-2.0.2
1 gem installed

$ bundle --version      
Bundler version 2.0.2
bundle --version  14.13s user 0.28s system 383% cpu 3.763 total

$ bundle
Using rake 12.3.2
Using bundler 2.0.2
Bundle complete! 1 Gemfile dependency, 2 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
bundle  25.62s user 0.40s system 407% cpu 6.383 total
```

The `bundler's executable "bundle/bundler" conflicts with /home/eregon/code/truffleruby-ws/truffleruby/mxbuild/truffleruby-jvm/jre/languages/ruby/bin/bundle/bundler` seem unfortunate, but don't prevent it to work.

So this seems like it should work fine in the next release, 19.3.

**Comment by nateberkopec** [comment]
> the remaining bug is that Bundler 2 doesn't seem used for a Gemfile.lock BUNDLED WITH 2.x.

Ah cool. I didn't really know what "default" meant. I agree with your assessment.

**Comment by eregon** [comment]
I'll close this issue since I think it's fixed in 19.3, and will comment here when 19.3 is released for verification.

**Comment by eregon** [comment]
@nateberkopec TruffleRuby 19.3.0 was released, could you verify this is fixed?

**Comment by nateberkopec** [comment]
Getting a new issue when compiling openssl so can't confirm or deny

```
ossl_x509cert.c:334:59: error: member reference
      type 'int' is not a pointer
  ...X509_get0_tbs_sigalg(x509)->algorithm)) {
     ~~~~~~~~~~~~~~~~~~~~~~~~~~  ^
```

**Comment by eregon** [comment]
Interesting, I never saw that one. Which version of openssl do you have?

**Comment by nateberkopec** [comment]
What would be the correct way for me to check that? I have homebrew installed in a nonstandard location so I should be exactly sure about which version Truffle would try to use.

**Comment by eregon** [comment]
Does the error message above have extra lines, which might indicate which headers it's using?

We check `brew --prefix openssl` and `/opt/local/include/openssl`:
https://github.com/oracle/truffleruby/blob/e4d5dfa3531e4376909a4be98afce063b2f00577/lib/truffle/truffle/openssl-prefix.rb

If the first one, could you tell me your `brew info openssl`?
And whether you also have `openssl@1.1` (`brew info openssl@1.1`)?
Does `/opt/local/include/openssl` exist on your system?

Setting `OPENSSL_PREFIX` to where openssl is installed might help as a workaround.
