### ISSUE TITLE
Unable to install rmagick 4.0.0 with TruffleRuby 19.3.1

### ISSUE THREAD

**Issue by jaime-rave-conichi** [oracle/truffleruby#1882]
I'm trying to install rmagick but I'm getting the following error:

`rmstruct.c:865:12: error: called object type 'VALUE' (aka 'void *') is not a function or function pointer
    return rb_funcall(Class_TypeMetric, rm_ID_new, 9`

It works fine with MRI 2.6.5. I'm attaching the logs.

The source code can be found here: https://github.com/rmagick/rmagick

[logs.txt](https://github.com/oracle/truffleruby/files/4086389/logs.txt)

**Comment by eregon** [comment]
Thanks for reporting the issue.
From a quick look this is caused by RMagic passing 9 arguments to `rb_funcall`, which is more than we ever found so far. The fix should be easy.

**Comment by eregon** [comment]
Note: we should probably add a C-API spec to test it and ensures it works for let's say 15 arguments.

**Comment by aardvark179** [comment]
@jaime-rave-conichi I have a fix for the problem you have reported, but you may still find issues on some systems. If ImageMagick has been built with OpenMP support then the compiler will be configured to add `-fopenmp` to the compiler flags, which the version of the LLVM tool chain we currently bundle does not support it at this time.

**Comment by jaimerave** [comment]
@aardvark179 awesome news! I'm currently not compiling with OpenMP so that's not a problem. Thanks a lot for your quick response.
