### ISSUE TITLE
Failed to require active_support/all

### ISSUE THREAD

**Issue by brauliobo** [oracle/truffleruby#2333]
On IRB

```
~/P/o/junction ❯❯❯ irb
cannot load such file -- wirble
truffleruby-21.1.0 :001 > require 'active_support/all'
Traceback (most recent call last):
        from /home/braulio/.rvm/rubies/truffleruby-21.1.0/bin/irb:42:in `<main>'
        from <internal:core> core/kernel.rb:400:in `load'
        from <internal:core> core/kernel.rb:400:in `load'
        from /home/braulio/.rvm/rubies/truffleruby-21.1.0/lib/gems/gems/irb-1.3.3/exe/irb:11:in `<top (required)>'
        from <internal:core> core/throw_catch.rb:36:in `catch'
        from <internal:core> core/throw_catch.rb:36:in `catch'
        from <internal:core> core/kernel.rb:437:in `loop'
        from <internal:core> core/kernel.rb:325:in `eval'
        from (irb):1:in `<top (required)>'
        from /home/braulio/.rvm/rubies/truffleruby-21.1.0/lib/mri/rubygems/core_ext/kernel_require.rb:92:in `require'
<internal:core> core/kernel.rb:236:in `gem_original_require': cannot load such file -- active_support/all (LoadError)
        ... 7 levels...
        from <internal:core> core/kernel.rb:325:in `eval'
        from (irb):1:in `<top (required)>'
        from /home/braulio/.rvm/rubies/truffleruby-21.1.0/lib/mri/rubygems/core_ext/kernel_require.rb:168:in `require'
        from <internal:core> core/kernel.rb:234:in `gem_original_require'
        from /home/braulio/.rvm/gems/truffleruby-21.1.0/gems/activesupport-4.2.11.3/lib/active_support/all.rb:3:in `<top (required)>'
        from /home/braulio/.rvm/rubies/truffleruby-21.1.0/lib/mri/rubygems/core_ext/kernel_require.rb:72:in `require'
        from <internal:core> core/kernel.rb:234:in `gem_original_require'
        from /home/braulio/.rvm/gems/truffleruby-21.1.0/gems/activesupport-4.2.11.3/lib/active_support/core_ext.rb:1:in `<top (required)>'
        from /home/braulio/.rvm/gems/truffleruby-21.1.0/gems/activesupport-4.2.11.3/lib/active_support/core_ext.rb:1:in `each'
        from /home/braulio/.rvm/gems/truffleruby-21.1.0/gems/activesupport-4.2.11.3/lib/active_support/core_ext.rb:2:in `block in <top (required)>'
        from /home/braulio/.rvm/rubies/truffleruby-21.1.0/lib/mri/rubygems/core_ext/kernel_require.rb:155:in `require'
        from <internal:core> core/kernel.rb:234:in `gem_original_require'
        from /home/braulio/.rvm/gems/truffleruby-21.1.0/gems/activesupport-4.2.11.3/lib/active_support/core_ext/object.rb:3:in `<top (required)>'
        from /home/braulio/.rvm/rubies/truffleruby-21.1.0/lib/mri/rubygems/core_ext/kernel_require.rb:72:in `require'
        from <internal:core> core/kernel.rb:234:in `gem_original_require'
        from /home/braulio/.rvm/gems/truffleruby-21.1.0/gems/activesupport-4.2.11.3/lib/active_support/core_ext/object/duplicable.rb:106:in `<top (required)>'
/home/braulio/.rvm/gems/truffleruby-21.1.0/gems/activesupport-4.2.11.3/lib/active_support/core_ext/object/duplicable.rb:111:in `<class:BigDecimal>': undefined method `new' for BigDecimal:Class (NoMethodError)
```

**Comment by eregon** [comment]
This error means that Rails 4 is too old and doesn't work on Ruby 2.7+ essentially. The same happens on CRuby 2.7.
Rails 5+ should work on Ruby 2.7+.

**Comment by brauliobo** [comment]
thank you @eregon !
