### ISSUE TITLE
numo-linalg gem doesn't build with truffleruby+graalvm-22.3.0 on Ubuntu 22.04 or Rocky 9 (RHEL)

### ISSUE THREAD

**Issue by jcasu** [oracle/truffleruby#2843]
truffleruby+graalvm-22.3.0 is having issues building numo-linalg
works fine, btw, on ruby 3.2.0.
Please see attached file for the error output.  Looks like a BLAS source macro isn't being defined.

many thanks.

[numo-error.txt](https://github.com/oracle/truffleruby/files/10512479/numo-error.txt)

**Comment by eregon** [comment]
Thank you for the report, I can reproduce it locally.

It sounds like `UNUSED` is not properly defined, not immediately clear why.
```
/home/eregon/.rubies/truffleruby-dev/lib/gems/gems/numo-linalg-0.1.7/ext/numo/linalg/blas/gen/../tmpl/nrm2.c:36:57: error: expected ')'
blas_s_dnrm2(int argc, VALUE const argv[], VALUE UNUSED(mod))
                                                        ^
/home/eregon/.rubies/truffleruby-dev/lib/gems/gems/numo-linalg-0.1.7/ext/numo/linalg/blas/gen/../tmpl/nrm2.c:36:13: note: to match this '('
blas_s_dnrm2(int argc, VALUE const argv[], VALUE UNUSED(mod))
            ^
```
