### ISSUE TITLE
String#to_d doesn't work properly in 1.0.0 RC14-dev

### ISSUE THREAD

**Issue by deepj** [oracle/truffleruby#1612]
This is used heavily in `dry-types`. The following code below works on TruffleRuby 1.0.0 RC13. Not on @chrisseaton nightly build.

```
truffleruby 1.0.0-rc14-dev-f6b387c4, like ruby 2.6.1, Interpreted [x86_64-darwin]
```

To reproduce:

```ruby
require 'bigdecimal'
require 'bigdecimal/util'

'1.23'.to_d
```

Error:

```
Traceback (most recent call last):
        2: from ~/.rubies/truffleruby-1.0.0-nightly/jre/languages/ruby/bin/irb:31:in `<main>'
        1: from (irb):4
NoMethodError (undefined method `to_d' for "1.23":String)
Did you mean?  to_f
               to_i
               to_r
               to_s
               to_c
```

**Comment by deepj** [comment]
@chrisseaton Here is a regression on the nightly build

**Comment by chrisseaton** [comment]
Ok thanks very much - we'll fix that tomorrow.

**Comment by nirvdrum** [comment]
@deepj As far as I can tell, this is only broken for `String`. Can you provide a case where it's broken on `Float` for you, please?

**Comment by deepj** [comment]
@deepj sorry for misleading in this case. `bigdecimal/util` wasn't required in the case. It works for `Float`. The problem seems to be only `String`.

**Comment by nirvdrum** [comment]
Great. Thanks for confirming!

**Comment by nirvdrum** [comment]
Thanks for the report! We accidentally dropped a Ruby implementation of the `String#to_d` method when we merged the stdlib files from MRI 2.6.1. MRI implements that method in C, but doing it in Ruby is better for us. I've added a spec to ensure this doesn't regress in the future. See f51f789ac0ffcf9871dd83bc374c0fc8e8c0da4a for more details.
